Repository GreenpixDev/ShiftAndroid, pull requests merged in 2022-07, with the labels that each got.

#9 Фикс репозитория событий и его юнит теста после изменения на бэке
  app/src/main/java/ru/cft/shift/scheduler/dto/EventColor.kt
  app/src/main/java/ru/cft/shift/scheduler/dto/EventInfoRequest.kt
  app/src/main/java/ru/cft/shift/scheduler/dto/EventInfoResponse.kt
  app/src/main/java/ru/cft/shift/scheduler/dto/EventType.kt
  app/src/main/java/ru/cft/shift/scheduler/repository/EventRepository.kt
  app/src/test/java/ru/cft/shift/scheduler/repository/EventRepositoryTest.kt
Labels: fix, testing

#8 Fix code style
  app/src/main/java/ru/cft/shift/scheduler/EventActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/RegistrationActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/layout/bottom_sheet_data_picker_finish.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#10 MVP паттерн для активити Макса
  app/src/androidTest/java/ru/cft/shift/scheduler/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ru/cft/shift/scheduler/MainActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/RegistrationActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/data/Month.kt
  app/src/main/java/ru/cft/shift/scheduler/di/component/AppComponent.kt
  app/src/main/java/ru/cft/shift/scheduler/di/component/ApplicationComponent.kt
  app/src/main/java/ru/cft/shift/scheduler/di/module/MvpPresenterModule.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/base/BaseActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/base/BaseFragment.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/base/BasePresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/CalendarActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/CalendarMvpPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/CalendarPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/event/modal/EventModalFragment.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/event/modal/EventModalMvpView.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/event/modal/EventModalPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/settings/SettingsFragment.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/settings/SettingsPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventMvpPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventMvpView.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/login/LoginActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/login/LoginMvpPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/login/LoginMvpView.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/login/LoginPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/register/RegistrationActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/register/RegistrationMvpPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/register/RegistrationMvpView.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/register/RegistrationPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/utils/CallbackBuilder.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_event.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/layout/bottom_sheet_color.xml
  app/src/main/res/layout/bottom_sheet_data_picker_finish.xml
  app/src/main/res/layout/bottom_sheet_data_picker_start.xml
  app/src/main/res/layout/bottom_sheet_event_type.xml
  app/src/main/res/values/strings.xml
Labels: enchancement, refactoring

#13 Добавлено возможность обновлять события (и синхронизация этого с бэком)
  app/src/main/java/ru/cft/shift/scheduler/data/Event.kt
  app/src/main/java/ru/cft/shift/scheduler/dto/EventInfoRequest.kt
  app/src/main/java/ru/cft/shift/scheduler/mapper/EventRequestMapper.kt
  app/src/main/java/ru/cft/shift/scheduler/mapper/EventResponseMapper.kt
  app/src/main/java/ru/cft/shift/scheduler/mapper/Mapper.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/base/BaseActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/base/BaseFragment.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/base/BasePresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/CalendarActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/CalendarPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/calendar/event/modal/EventModalFragment.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventMvpPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventMvpView.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/event/EventPresenter.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/register/RegistrationActivity.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/register/RegistrationMvpView.kt
  app/src/main/java/ru/cft/shift/scheduler/ui/register/RegistrationPresenter.kt
  app/src/test/java/ru/cft/shift/scheduler/repository/EventRepositoryTest.kt
Labels: enchancement
